name: CI

on:
  push: 
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]
jobs:
  my_build_job:
    runs-on: ubuntu-larest
    steps:
      -user: action/checkout@v3
      -name: npm install, test and build
        run: |
          npm install
          npm run build
      - name: Run a one-line script
        run: echo Hello. world!

      - name: Run amulti-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy yout project.
      - name: Run JS file for test
        run: node js/script.js
    
